import { resolve } from 'node:path'

import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'
import { doors, serves } from 'kehikot-module-protocol/serve'
import { defineConfig } from 'vite'

import { BUILD, MANIFEST, TICKET, answer } from './doors.ts'
import { ID, PREFERRED_PORT } from './manifest.ts'

/**
 * Every door this app answers on is `doors()` from the protocol, served by the one process that
 * serves the page: the manifest at both well-known paths, `/app` (generated, with the write ticket
 * and the build printed into it, `no-store`, `frame-ancestors`), and `/healthz`, `/mcp` and
 * `/api/*` through `answer` in `doors.ts`. See the protocol's docs/module-plumbing.md.
 *
 * ## Why they cannot be a second server
 *
 * A module is ONE ORIGIN or it is nothing. The page fetches `/api/notes` and `/api/note` as
 * relative paths; a store on a second port would make every one of those cross-origin, and this
 * app could not read its own notes inside the frame it lives in. So the store is middleware in
 * front of the same server that serves the page, and `doors.ts` holds the deciding without holding
 * a socket.
 *
 * `/app` has to be claimed before Vite's resolver sees it, because this repository has a
 * `src/app.tsx` and under Vite dev an extensionless `/app` next to it answers `200
 * text/javascript`. `doors()` claims it first, so the plugin order below is load-bearing.
 */

/**
 * The dev server, and the one line missing from it that decides whether the
 * ticket in this page is worth anything.
 *
 * ## No `server.cors` — this module declares storage instead
 *
 * Modules that hold nothing set `cors: true` and have to. A host frames a
 * module WITHOUT `allow-same-origin` unless its manifest declares storage,
 * which puts the page on an opaque origin — and `<script type="module">` is
 * ALWAYS fetched in CORS mode, so with no permissive header not one script in
 * the page runs. The document loads, `load` fires, the host greets it, and
 * nothing answers. `curl` cannot see it, being unsubject to CORS; only the
 * browser console can. That has cost this codebase days.
 *
 * This module must not go that way, for a reason those modules do not have: it
 * OWNS data and takes writes, gated on a ticket printed into `/app`. A
 * permissive `Access-Control-Allow-Origin` means any page in any tab can read
 * that document, and therefore that ticket, off loopback — and then write here.
 * Measured on a sibling module rather than theorised, before it was moved to
 * this shape:
 *
 *     $ curl -H 'Origin: https://evil.example' http://127.0.0.1:7840/app
 *     Access-Control-Allow-Origin: *
 *     ...ticket" type="application/json">"e75d4d01-…
 *
 * So the manifest declares `storage: true` and this line is absent. With a real
 * origin, this page's scripts and its `/api` calls are ordinary same-origin
 * requests: no CORS is involved at all, nothing is offered to strangers, and the
 * ticket is unreadable from anywhere but inside.
 *
 * ## No alias for `kehikot-module-protocol`
 *
 * There used to be one, in every app here, pointing at the protocol's source in
 * the repository they all used to live in. It is gone and must not come back:
 * the package's `exports` are correct, reaching past them is what made a whole
 * class of bug possible, and a module that resolved its contract differently
 * from the host it talks to is a module testing something nobody ships.
 *
 * The `@` alias below is a different thing entirely — it points inside this
 * repository, at `src`, and is what shadcn's generated components import
 * through.
 *
 * ## There is no `build` script, and no `build` here worth having
 *
 * `run.sh` runs Vite. Nothing serves a `dist/`, so a build would produce a
 * second answer to "what does this page say" which disagrees with the first the
 * moment somebody edits `src/`. Several modules in this workspace carry a
 * `"build": "vite build"` that cannot succeed, because the page is generated by
 * `doors()` and there is no `index.html` for Rollup to start from.
 * This one does not add another.
 *
 * ## And no `server.port`, because `serves()` is what decides it
 *
 * 7940 used to be written in `run.sh` and again in `register.ts`, and true in
 * neither of them the moment anything else had the port: `--strictPort` meant
 * this app printed `Error: Port 7940 is already in use` and exited, so a program
 * with nothing to do with notes could stop the notes from opening. The number is
 * now `PREFERRED_PORT` in `manifest.ts`, said once beside the id, and read from
 * there by this file and by `register.ts` both.
 *
 * `serves()` — first in the list below, because it has to claim the port before
 * anything else in this config gets a chance to want one — takes a free 7940
 * silently, ends the start cleanly if this module is already answering there
 * rather than making a second copy of it, and otherwise moves loudly to the next
 * free port and rewrites the registration to wherever the server actually bound.
 * That last part is what makes the drift safe: a second copy of this app would be
 * two writers on one `notes.json`, and a registration naming a port this app has
 * drifted off is one the host sweeps to find nothing.
 */
export default defineConfig({
  /**
   * `base: './'`, because this page is served at `/app` here and framed by a
   * host at whatever address that host wrote down. Absolute asset paths are
   * correct in the first case and a guess in the second; relative ones are a
   * fact in both, because the browser resolves them against the document it
   * just fetched.
   */
  base: './',
  plugins: [
    serves({ id: ID, prefer: PREFERRED_PORT }),
    doors({ manifest: MANIFEST, answer, build: BUILD, page: { title: 'Notes', ticket: TICKET } }),
    react(),
    tailwindcss(),
  ],
  resolve: { alias: { '@': resolve(import.meta.dirname, 'src') } },
})
